collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6282881
  brandStrength: 0.2939068
  lightness: 0.8023686
  brandColors:
    - '#FFFFFB'
    - '#1E2720'
    - '#76A442'
    - '#A2C6FF'
    - '#D0B3A4'
  rhythmicContrast: 0.7275985
typography_spectrum: 0.1057348
layout_spectrum: 1
name: TrickPit
